# Generated by Django 4.2.21 on 2025-05-13 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='authors/images/')),
                ('firts_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('writer', 'Writer')], default='admin', max_length=255)),
                ('about_author', models.TextField()),
            ],
        ),
    ]
